<?php 
include("includes/function.php"); 
require_once 'dompdf/vendor/autoload.php';

use Dompdf\Dompdf;
if(isset($_GET['AssetsuserPIN'])){
    $userPIN = $_GET['AssetsuserPIN'];

    // Ensure database connection is defined
    if (!isset($con)) {
        die("Database connection not found.");
    }
    // Fetch data from database
    $sql = mysqli_query($con, "SELECT * FROM `assets` WHERE usePIN='$userPIN'");
    if (!$sql) {
        die("Error in query: " . mysqli_error($con));
    }
    // Fetch all rows properly
    $rows = mysqli_fetch_all($sql, MYSQLI_ASSOC);

    $i = 0;

    // Start building HTML for PDF
    $html = '
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Report</title>
        <style>
            body {
                font-family: fangsong;
            }
            h2 {
                text-align: center;
                font-weight: bold;
            }
            table {
                border-collapse: collapse;
                width: 100%;
            }
            td, th {
                border: 1px solid grey;
                padding: 8px;
                text-align: center;
            }
            .my-table {
                color: grey;
                font-weight: normal;
            }
        </style>
    </head>
    <body>
    <div style="text-align:center">
        <p style="font-size:37px;color:#1f3864">Blue <span style="color:#00b0f0">River</span></p>
        <h5>Assets Report</h5>
        <p style="margin-top:-10px;text-align:justify">Blue River, we help you turn your finances and properties into opportunities. 
                                Whether it’s achieving your dreams or fulfilling specific needs, 
                                we guide you to unlock the full potential of your assets, 
                                creating tailored strategies to transform what you have into what you truly desire.</p></p>
    </div>
        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Transaction Type</th>
                    <th>Amount</th>
                    <th>Description</th>
                    <th>Asset Type</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>';

    // Loop through data and populate table
    foreach ($rows as $row) {
        $i++;
        $html .= '
            <tr>
                <td>' . $i . '</td>
                <td>' . htmlspecialchars($row['transcation_type']) . '</td>
                <td>' . htmlspecialchars($row['amount']) . '</td>
                <td>' . htmlspecialchars($row['description']) . '</td>
                <td>' . htmlspecialchars($row['asset_type']) . '</td>
                <td>' . date("d M, Y", strtotime($row['date'])) . '</td>
            </tr>';
    }

    $html .= '
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="6" class="my-table">This report has been Generated by <b class="fw-bold"style="color:#1f3864">Blue <b style="color:#00b0f0">River</b></b>.</th>
                </tr>
            </tfoot>
        </table>
    </body>
    </html>';

    // Initialize Dompdf
    $dompdf = new Dompdf();
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    $dompdf->stream("Assets-$userPIN.pdf"); // Inline view instead of forced download
}
else if(isset($_POST['FilterAssetReport'])){
    $userPIN = $_POST['userPIN'];
    $assetType = $_POST['assetType'];
    $startDate = $_POST['startDate'];
    $endDate = $_POST['endDate'];
    $currentDate = date('Y-m-d');

    if($assetType != "" && $assetType != "all"){
        $sql = mysqli_query($con, "SELECT * FROM `assets` WHERE `usePIN`='$userPIN' AND `asset_type`='$assetType'");
    }else if($assetType != "" && $assetType == "all"){
        $sql = mysqli_query($con, "SELECT * FROM `assets` WHERE `usePIN`='$userPIN'");
    }else if($startDate !=""){
        $sql = mysqli_query($con, "SELECT * FROM `assets` WHERE `usePIN`='$userPIN' AND (date BETWEEN '$startDate' AND '$currentDate')");
    }else if($endDate !=""){
        $sql = mysqli_query($con, "SELECT * FROM `assets` WHERE `usePIN`='$userPIN' AND (date BETWEEN '$endDate' AND '$currentDate')");
    }else if($startDate !="" && $endDate != ""){
        $sql = mysqli_query($con, "SELECT * FROM `assets` WHERE `usePIN`='$userPIN' AND (date BETWEEN '$startDate' AND '$endDate')");
    }

    $rows = mysqli_fetch_all($sql, MYSQLI_ASSOC);

    $i = 0;
    
    // Start building HTML for PDF
    $html = '
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Report</title>
        <style>
            body {
                font-family: fangsong;
            }
            h2 {
                text-align: center;
                font-weight: bold;
            }
            table {
                border-collapse: collapse;
                width: 100%;
            }
            td, th {
                border: 1px solid grey;
                padding: 8px;
                text-align: center;
            }
            .my-table {
                color: grey;
                font-weight: normal;
            }
        </style>
    </head>
    <body>
    <div style="text-align:center">
        <p style="font-size:37px;color:#1f3864">Blue <span style="color:#00b0f0">River</span></p>
        <h5>Assets Report</h5>
        <p style="margin-top:-10px;text-align:justify">Blue River, we help you turn your finances and properties into opportunities. 
                                Whether it’s achieving your dreams or fulfilling specific needs, 
                                we guide you to unlock the full potential of your assets, 
                                creating tailored strategies to transform what you have into what you truly desire.</p></p>
    </div>
        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Transaction Type</th>
                    <th>Amount</th>
                    <th>Description</th>
                    <th>Asset Type</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>';
    
    // Loop through data and populate table
    foreach ($rows as $row) {
        $i++;
        $html .= '
            <tr>
                <td>' . $i . '</td>
                <td>' . htmlspecialchars($row['transcation_type']) . '</td>
                <td>' . htmlspecialchars($row['amount']) . '</td>
                <td>' . htmlspecialchars($row['description']) . '</td>
                <td>' . htmlspecialchars($row['asset_type']) . '</td>
                <td>' . date("d M, Y", strtotime($row['date'])) . '</td>
            </tr>';
    }
    
    $html .= '
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="6" class="my-table">This report has been Generated by <b class="fw-bold"style="color:#1f3864">Blue <b style="color:#00b0f0">River</b></b>.</th>
                </tr>
            </tfoot>
        </table>
    </body>
    </html>';
    
    // Initialize Dompdf
    $dompdf = new Dompdf();
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    $dompdf->stream("Assets-$userPIN.pdf"); // Inline view instead of forced download 
}
else{
    echo "<script>window.open('Dashboard.php', '_self')</script>";
}

?>
